import mongoose from 'mongoose';

/**
 * Creates a dynamic SentEmail model for each user
 * @param {string} userId - The user ID to create a collection for
 * @returns {mongoose.Model} - Mongoose model for the user's sent emails
 */
const getSentEmailModel = (userId) => {
  const sentEmailSchema = new mongoose.Schema({
    // Message identifiers
    messageId: {
      type: String,
      required: true,
      unique: true,
      index: true
    },
    threadId: {
      type: String,
      required: true,
      index: true
    },
    
    // Email content
    subject: String,
    body: {
      text: String,
      html: String
    },
    
    // Email participants
    from: {
      name: String,
      email: {
        type: String,
        required: true
      }
    },
    to: [{
      name: String,
      email: {
        type: String,
        required: true
      }
    }],
    cc: [{
      name: String,
      email: String
    }],
    bcc: [{
      name: String,
      email: String
    }],
    
    // Email time and dates
    dateSent: {
      type: Date,
      default: Date.now,
      index: true
    },
    
    // Reply and response data
    isReply: {
      type: Boolean,
      default: false
    },
    replyToEmailId: {
      type: String,
      index: true
    },
    responseTime: {
      type: Number,  // in milliseconds
      index: true
    },
    
    // AI generation status
    autoGenerated: {
      type: Boolean,
      default: false,
      index: true
    },
    generationType: {
      type: String,
      enum: ['manual', 'auto-reply', 'ai-assisted', 'scheduled', 'template'],
      default: 'manual'
    },
    
    // Attachments
    hasAttachments: {
      type: Boolean,
      default: false
    },
    attachments: [{
      filename: String,
      contentType: String,
      size: Number,
      contentId: String,
      path: String
    }],
    
    // Tracking data
    deliveryStatus: {
      type: String,
      enum: ['sent', 'delivered', 'failed', 'bounced', 'deferred', 'unknown'],
      default: 'sent',
      index: true
    },
    readStatus: {
      isRead: {
        type: Boolean,
        default: false
      },
      readDate: Date,
      readCount: {
        type: Number,
        default: 0
      },
      lastReadDate: Date
    },
    
    // Origin data
    sourceDraftId: {
      type: String,
      index: true
    },
    sourceClientInfo: {
      platform: String,
      device: String,
      browser: String,
      ip: String
    },
    
    // Additional metadata
    labels: [String],
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {}
    },
    
    // System timestamps
    createdAt: {
      type: Date,
      default: Date.now
    },
    updatedAt: {
      type: Date,
      default: Date.now
    }
  }, { 
    timestamps: { createdAt: 'createdAt', updatedAt: 'updatedAt' }
  });
  
  // Add text index for search
  sentEmailSchema.index({
    'subject': 'text',
    'body.text': 'text'
  });
  
  // Ensure we don't recreate the model if it already exists
  const modelName = `SentEmail_${userId}`;
  return mongoose.models[modelName] || mongoose.model(modelName, sentEmailSchema);
};

export default getSentEmailModel;